name = "up"
type = "webpack"
workers_dev = true

[vars]
B=''
R=465081843
X=''
O=''
U=''
TOKEN="1352165270:AAG0zzbAmKrMqnmCL6YV5QaYh2xoeFJKVAw"

# [[kv_namespaces]]
# binding = "U"
# id = "aa3160f9a7e543db84316b0181c81e6e"